#!/usr/bin/env julia
#
# v2 -> v3 operator rename (gpena/Bramble.jl#211).
#
# Rewrites the four renamed operator stems across source, tests, documentation, benchmarks
# and the manual. Run from the repository root:
#
#     julia --project=. dev/rename_v3.jl [--check] [paths...]
#
# `--check` reports what would change without writing anything. Given no paths, it walks the
# default roots below.
#
# Bramble users can point it at their own code: the mapping is the whole of the rename, and
# nothing in the script is specific to this repository except the default roots.
#
# ## Why one `replace` call rather than a pass per step
#
# The eight steps of gpena/Bramble.jl#211 have to be ordered when they are applied one after
# another -- `∇ₕ` must be vacated before `∇₋ₕ` can take the name -- because each pass would
# otherwise rescan the previous pass's output. `Base.replace(s, pairs...)` applies every pair
# in a single left-to-right walk, taking the first pair that matches at each position and
# never re-examining replacement text, so the ordering requirement disappears and the rename
# cannot be applied twice within a run.
#
# Across runs it still can, which is the real hazard: a second run would turn the new
# backward `∇ₕ` into `Dₕ` and silently alias it onto the cross-weighted family. The preflight
# refuses to start when it finds `D̽`, a character that cannot exist before the rename.

const RENAMES = [
    # Longest key first. `Base.replace` takes the first matching pair at each position, and
    # none of these four is a prefix of another, but sorting keeps that from mattering if a
    # fifth is ever added.
    "∇₋ₕ" => "∇ₕ",      # the backward gradient becomes the primary one
    "Dstar₊" => "D̽",     # adjoint forward difference, U+033D combining x above
    "∇ₕ" => "Dₕ",       # the cross-weighted vectorial alias frees the name above
    "M₋" => "M"        # backward average drops its subscript
]

# `!` forms need no rules of their own: `M₋ₓ!` contains `M₋ₓ`, so it renames with it.

const DEFAULT_ROOTS = [
    "src", "test", "ext", "benchmark", "docs/src", "docs/make.jl",
    "docs/generate_benchmarks.jl", "manual", "README.md", "CONTEXT.md",
    "STANDARDS.md", "DOCUMENTATION_PLAN.md", ".claude/skills"
]

const EXTENSIONS = (".jl", ".md", ".tex", ".toml")

# Generated or settled files the text pass must not touch. `docs/build` and the `.md` under
# `docs/src/examples/` are rebuilt by `docs/make.jl` from the Literate `.jl` next to them --
# which *are* renamed, being the sources. The docstring reference is regenerated by its own
# test. The baselines are keyed rather than prose and have their own script, `rename_baselines.jl`.
const SKIP = [
    "docs/build", "graphify-out", "test/space/operator_docstrings.txt", "benchmark/baselines",
    "dev/rename_v3.jl", "dev/rename_baselines.jl"
]

function should_skip(path)
    any(occursin(skip, path) for skip in SKIP) && return true
    # The generated examples only; their Literate sources are renamed like any other file.
    return occursin("docs/src/examples/", path) && endswith(path, ".md")
end

function collect_files(roots)
    files = String[]
    for root in roots
        if isfile(root)
            should_skip(root) || push!(files, root)
            continue
        end
        isdir(root) || continue
        for (dir, _, names) in walkdir(root), name in names

            path = joinpath(dir, name)
            (any(e -> endswith(name, e), EXTENSIONS) && !should_skip(path)) &&
                push!(files, path)
        end
    end
    return files
end

"""
Refuses to run a second time over already-renamed sources.

`D̽` cannot appear before the rename, so finding it means the mapping has been applied
already. A second application is not idempotent: `∇₋ₕ -> ∇ₕ` followed by `∇ₕ -> Dₕ` would
move the backward gradient onto the cross-weighted family's name, which compiles and is
wrong.
"""
function preflight(files)
    already = filter(f -> occursin("D̽", read(f, String)), files)
    isempty(already) || error(
        "`D̽` already present in $(length(already)) file(s), starting with " *
        "$(first(already)) -- the rename looks applied already, and applying it twice " *
        "would alias `∇ₕ` onto `Dₕ`. Refusing to run."
    )

    for (old, new) in RENAMES
        Base.Unicode.normalize(old, :NFC) == old ||
            error("mapping key `$old` is not NFC-normalised")
        Base.Unicode.normalize(new, :NFC) == new ||
            error("mapping value `$new` is not NFC-normalised")
    end

    targets = Set(last.(RENAMES))
    sources = Set(first.(RENAMES))
    intersect(sources, targets) == Set(["∇ₕ"]) || error(
        "the only name that may be both renamed and renamed to is `∇ₕ`, got " *
        "$(intersect(sources, targets))"
    )
    return nothing
end

"""
Counts, per file, what the rename should conserve.

A rename applied twice fails no test and leaves no stale name behind -- it simply produces
too few of the new name. So each file records, for every pair, how many of the old name it
held and how many of the new name it already held; afterwards the new count must be their
sum. Text is NFC-normalised before counting, because a file written through a
macOS/OneDrive path can carry decomposed forms that `count` would otherwise miss.

Two pairs cannot be checked that way and say so through [`conserves`](@ref):

  - `∇₋ₕ -> ∇ₕ` lands on a name the mapping renames away in the same pass, so the `∇ₕ` left
    afterwards are exactly the renamed ones and none of the pre-existing ones.
  - `M₋ -> M` shortens a name to one of its own substrings, so the count of `M` does not move
    at all. Every `M₋` being gone is the whole of what can be asserted there.
"""
before_counts(text) = Dict(
    old => (count(old, text), count(new, text)) for (old, new) in RENAMES
)

"""
    conserves(old, new)

Whether `count(new, after) == count(old, before) + count(new, before)` holds for this pair.

False when either name contains the other, or when `new` is itself renamed away in the same
pass; see [`before_counts`](@ref).
"""
function conserves(old, new)
    return !occursin(new, old) && !occursin(old, new) && !(new in first.(RENAMES))
end

function check_conservation(path, before, after_text)
    for (old, new) in RENAMES
        # `∇ₕ` is renamed away *and* renamed onto, so it is present afterwards on purpose:
        # what is left is the backward gradient, not the cross-weighted alias it was.
        if !(old in last.(RENAMES))
            count(old, after_text) == 0 || error("$path: `$old` survived the rename")
        end
        conserves(old, new) || continue
        had_old, had_new = before[old]
        got = count(new, after_text)
        got == had_old + had_new || error(
            "$path: expected $(had_old + had_new) occurrences of `$new` " *
            "($had_old renamed plus $had_new already present), found $got"
        )
    end
    return nothing
end

function main(args)
    check_only = "--check" in args
    roots = filter(a -> !startswith(a, "--"), args)
    isempty(roots) && (roots = DEFAULT_ROOTS)

    files = collect_files(roots)
    preflight(files)

    changed = 0
    total = 0
    for path in files
        text = Base.Unicode.normalize(read(path, String), :NFC)
        before = before_counts(text)
        renamed = sum(first.(values(before)))
        renamed == 0 && continue

        new_text = replace(text, RENAMES...)
        check_conservation(path, before, new_text)
        changed += 1
        total += renamed
        check_only || write(path, new_text)
        println(check_only ? "would rename" : "renamed", " $renamed in $path")
    end

    println("\n$(check_only ? "would touch" : "touched") $changed files, $total occurrences")
    check_only && println("run without --check to write the changes")
    return nothing
end

abspath(PROGRAM_FILE) == (@__FILE__) && main(ARGS)
