# average.jl
# Discrete averaging operators for Bramble lazy AST

# ==============================================================================
# Struct Definitions
# ==============================================================================

"""
    BackwardAverage{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node representing a backward spatial averaging operator acting in dimension `Dim`.
"""
struct BackwardAverage{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

"""
    ForwardAverage{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node representing a forward spatial averaging operator acting in dimension `Dim`.
"""
struct ForwardAverage{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

"""
    ShiftNode{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node representing a stencil shift operation by `shift_amount` grid points in dimension `Dim`.
"""
struct ShiftNode{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    shift_amount::Int
    inner_op::OpType
end

# ==============================================================================
# User-Facing API & Overloads
# ==============================================================================
#
# The two average families, generated by `@node_family` (`node_family.jl`), as the
# differences are (gpena/Bramble.jl#74). `avg_backward`/`avg_forward` and
# `vectorial_avg_backward`/`vectorial_avg_forward` were the hand-written constructors behind
# them; the first pair took the direction as a bare `Int` and wrote it straight into the
# node's type, which is type-unstable by construction, and the second pair was `Mₕ`/`M₊ₕ`
# under another name.
#
# `dispatch_alias` puts the direction argument on `Mₕ`/`M₊ₕ` rather than minting a bare `M`,
# for the reason `space/operators/average.jl` records: `M` is what finite-element code calls
# its mass matrix, and `using Bramble` would take the name away. `Mₕ(U)` is still the tuple;
# `Mₕ(U, Val(2))` is the `y` node.

@node_family(node=BackwardAverage,
    stem=M,
    what="backward spatial average",
    dispatch_alias=Mₕ,
    vectorial_alias=Mₕ)

@node_family(node=ForwardAverage,
    stem=M₊,
    what="forward spatial average",
    dispatch_alias=M₊ₕ,
    vectorial_alias=M₊ₕ)

"""
    shift_op(op::LazyOp{D}, dim::Int, amount::Int) where D

Shifts the stencil of `op` by `amount` grid points in dimension `dim`.
"""
function shift_op(op::LazyOp{D}, dim::Int, amount::Int) where {D}
    return ShiftNode{D, dim, typeof(op)}(amount, op)
end

# ==============================================================================
# Zero-Allocation Stencil Evaluators
# ==============================================================================

# Both taps of an average carry the same weight, so the mask is the whole coefficient.
@inline _stencil_taps(::BackwardAverage) = (Val(0), Val(-1))
@inline _stencil_taps(::ForwardAverage) = (Val(1), Val(0))

@inline function _stencil_weights(
        op::BackwardAverage{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    T = eltype(space)
    mask = I[Dim] == 1 ? zero(T) : T(1) / 2
    return (mask, mask)
end

@inline function _stencil_weights(
        op::ForwardAverage{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    T = eltype(space)
    mask = I[Dim] == npoints(mesh(space), Tuple)[Dim] ? zero(T) : T(1) / 2
    return (mask, mask)
end

@inline function local_stencil(
        op::ShiftNode{D, Dim}, space, I::CartesianIndex{D}, markers, lin_idx::Int
) where {D, Dim}
    inner = local_stencil(op.inner_op, space, I, markers, lin_idx)
    return _shift_node_stencil(
        stencil_shift_trait(op.inner_op), op, inner, space, I, markers
    )
end

@inline _shift_node_stencil(
    ::TranslationInvariantStencil,
    op::ShiftNode{D, Dim},
    inner,
    space,
    I::CartesianIndex{D},
    markers
) where {D, Dim} = shift_stencil(inner, Val(Dim), op.shift_amount)

# `shift_op` has no mask of its own: every other wrapper that reaches a neighbour
# (differences, averages, jumps) computes one first and multiplies a clamped boundary read by
# it, which is what makes `_clamped_shift`'s "clamp now, a zero mask absorbs it" contract safe
# for them. Nothing here would absorb it for a source: relabelling an offset is safe
# unclamped, since the caller's own bounds check drops the whole entry when the offset lands
# out of range, but a source has already been reduced to a value by the time this runs, with
# no offset left for that check. A source shifted off the grid therefore reads as zero here:
# an empty stencil, the same "missing neighbour is zero" convention the masked stencils use,
# mirroring how `RegionRestriction` already spells "contributes nothing here".
#
# An interpolation is not a source, and clamping is its own correct behaviour: `locate_cell`
# (`space/operators/interpolation.jl`) clamps every point it is given, in-grid or not, by
# design (`πₕ`'s own docstring calls this extrapolation along the boundary cell's slope, not
# a missing-neighbour convention to override). So only a source-only inner operand gets the
# in-grid check; anything else falls through to the ordinary clamped re-evaluation.
@inline function _shift_node_stencil(
        ::PointDependentStencil,
        op::ShiftNode{D, Dim},
        inner,
        space,
        I::CartesianIndex{D},
        markers
) where {D, Dim}
    if _is_source_only(op.inner_op)
        Ishift = I + _stencil_step(Val(Dim), Val(D)) * op.shift_amount
        _in_grid(space, Ishift) || return ()
        return local_stencil(
            op.inner_op, space, Ishift, markers, LinearIndices(indices(mesh(space)))[Ishift]
        )
    else
        return shifted_inner_stencil(
            op.inner_op, inner, space, I, markers, Val(Dim), op.shift_amount
        )
    end
end

# ==============================================================================
# AST Resolution
# ==============================================================================

"""
    AverageNode{D, Dim}

Either average node over a `D`-dimensional space, averaging along `Dim`.

The pair carries the same parameters and differs only in which neighbour it reaches, so
anything reading the direction rather than choosing a stencil is written against this alias.
"""
const AverageNode{D, Dim} = Union{BackwardAverage{D, Dim}, ForwardAverage{D, Dim}}

function resolve_ast(op::ShiftNode{D, Dim}) where {D, Dim}
    return ShiftNode{D, Dim, typeof(resolve_ast(op.inner_op))}(
        op.shift_amount, resolve_ast(op.inner_op)
    )
end

# `ShiftNode` carries a second field, so it writes its own binder rather than taking the one
# `@node_family` generates (form/operators/interpolation.jl explains the pass).
function _bind_interp_spaces(
        op::ShiftNode{D, Dim}, trial_leaf, test_leaf
) where {D, Dim}
    inner = _bind_interp_spaces(op.inner_op, trial_leaf, test_leaf)
    return ShiftNode{D, Dim, typeof(inner)}(op.shift_amount, inner)
end

# ==============================================================================
# Expression rendering (gpena/Bramble.jl#274)
# ==============================================================================

expression(op::BackwardAverage{D, Dim}) where {D, Dim} = "M$(_BRAMBLE_var2symbol[Dim])($(expression(op.inner_op)))"
expression(op::ForwardAverage{D, Dim}) where {D, Dim} = "M₊$(_BRAMBLE_var2symbol[Dim])($(expression(op.inner_op)))"
function expression(op::ShiftNode{D, Dim}) where {D, Dim}
    "shift($(expression(op.inner_op)), $(_BRAMBLE_var2symbol[Dim]), $(op.shift_amount))"
end
