# difference.jl
# Discrete finite difference operators for Bramble lazy AST

# ==============================================================================
# Struct Definitions
# ==============================================================================

"""
    BackwardDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node representing a backward finite difference operator acting in dimension `Dim`.
"""
struct BackwardDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

"""
    ForwardDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node representing a forward finite difference operator acting in dimension `Dim`.
"""
struct ForwardDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

# ==============================================================================
# User-Facing API & Overloads
# ==============================================================================
#
# The two one-sided families, generated by `@node_family` (`node_family.jl`). What was
# written out here -- `grad_backward`/`grad_forward`, six subscript one-liners, the two
# gradients and their tuple methods -- is the same text for both families but for the node
# name, so it is now said once (gpena/Bramble.jl#74).
#
# `D₋(op, Val(1))` is the entry point the subscripts forward through, and it is a method of
# the same `D₋` the space layer applies to a grid function: the argument decides whether a
# difference is computed now or a node is built to compute it during assembly.

@node_family(node=BackwardDifference,
    stem=D₋,
    what="backward finite difference",
    vectorial_alias=∇ₕ,
    componentwise=true)

@node_family(node=ForwardDifference,
    stem=D₊,
    what="forward finite difference",
    vectorial_alias=∇₊ₕ,
    componentwise=true)

# ==============================================================================
# Zero-Allocation Stencil Evaluators
# ==============================================================================

# Taps and weights, consumed by the one `local_stencil` in `form/stencil_eval.jl` and --
# the point of declaring them -- by `stencil_offsets` in `form/stencil_pattern.jl`, which
# used to spell the same reach out a second time (gpena/Bramble.jl#70).
@inline _stencil_taps(::BackwardDifference) = (Val(0), Val(-1))
@inline _stencil_taps(::ForwardDifference) = (Val(1), Val(0))

@inline function _stencil_weights(
        op::BackwardDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    h = spacing(mesh(space), I, Dim)
    mask = I[Dim] == 1 ? 0 : 1
    return (mask / h, -mask / h)
end

@inline function _stencil_weights(
        op::ForwardDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    m = mesh(space)
    h = forward_spacing(m, I, Dim)
    mask = I[Dim] == npoints(m, Tuple)[Dim] ? 0 : 1
    return (mask / h, -mask / h)
end

# ==============================================================================
# AST Resolution
# ==============================================================================

# `resolve_ast` for both is generated with the families above.

# ==============================================================================
# Direct integration helpers for the form AST (ast.jl)
# ==============================================================================

"""
    DifferenceNode{D, Dim}

Either one-sided difference node over a `D`-dimensional space, differencing along `Dim`.

The two carry the same parameters, so anything that reads only the *direction* off the
node is written against this alias and stays symmetric between them by construction.

Not everything can be: `inner₊` takes backward differences alone, because the staggered
weights it carries are the ones the summation-by-parts identity pairs with a backward
difference. Use this alias where the distinction genuinely does not arise.
"""
const DifferenceNode{D, Dim} = Union{BackwardDifference{D, Dim}, ForwardDifference{D, Dim}}

# ==============================================================================
# The remaining difference families
# ==============================================================================
#
# Three more differences, each a symbolic counterpart of an operator the space layer
# already provides. These nodes assemble through their stencils; the space layer's matrix
# forms of the same three operators are what those stencils are tested against.
#
# The boundary convention is the one the one-sided nodes already use: the offsets stay and
# the coefficients go to zero. A truncated point contributes nothing while the stencil
# keeps the same shape, which is what lets the assembly loop stay branch-free.
#
# Writing `h` for `spacing` (xᵢ - xᵢ₋₁) and `hf` for `forward_spacing` (xᵢ₊₁ - xᵢ), as the
# space layer's own docstrings do.

"""
    CenteredDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node for the centered difference along `Dim`,

```math
Dc(u)_i = \\frac{u_{i+1} - u_{i-1}}{h_i + h_{i+1}}
```

Truncated at both ends of `Dim`, having no neighbour on one side.
"""
struct CenteredDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

"""
    StarDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node for the starred forward difference along `Dim`,

```math
D^{*}_{+}(u)_i = \\frac{u_{i+1} - u_i}{(h_i + h_{i+1})/2}
```

The forward difference over the *averaged* spacing rather than the forward one, which is
what makes the discrete integration by parts close. Truncated at the far end of `Dim`.
"""
struct StarDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

"""
    CrossWeightedDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node for the cross-weighted centered difference along `Dim`,

```math
D_h(u)_i = \\frac{h_i}{h_i + h_{i+1}} D_{-}(u)_{i+1}
         + \\frac{h_{i+1}}{h_i + h_{i+1}} D_{-}(u)_i
```

The same two one-sided differences the centered difference combines, weighted by the
*opposite* spacings. That swap is what makes it second order on a non-uniform grid where
`Dc` is first, and the two coincide when the spacing is constant. Truncated at both ends.
"""
struct CrossWeightedDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

# The three extended families, as `@node_family` calls like the one-sided pair above. Their
# prose is thinner than the space layer's: the boundary conventions and the order-of-accuracy
# comparisons that `Dcₓ` and `Dₕₓ` carry there describe arithmetic, and the arithmetic of
# these nodes is `_stencil_weights` below, which documents itself.
#
# `Dₕ` is the one family whose stem and tuple-valued alias are the same name, so `Dₕ(op)`
# gives the `D`-tuple and `Dₕ(op, Val(2))` the `y` node. They coexist by arity, which is the
# decision gpena/Bramble.jl#140 asked to be made on purpose rather than by merge.

@node_family(node=CenteredDifference,
    stem=Dc,
    what="centered difference",
    vectorial_alias=Dcₕ)

@node_family(node=StarDifference,
    stem=D̽,
    what="starred forward difference",
    vectorial_alias=D̽ₕ)

@node_family(node=CrossWeightedDifference,
    stem=Dₕ,
    what="cross-weighted centered difference",
    vectorial_alias=Dₕ)

# --- Stencils --------------------------------------------------------------------- #

@inline _stencil_taps(::CenteredDifference) = (Val(1), Val(-1))
@inline _stencil_taps(::StarDifference) = (Val(1), Val(0))

@inline function _stencil_weights(
        op::CenteredDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    m = mesh(space)
    # no neighbour on one side at either end
    mask = (I[Dim] == 1 || I[Dim] == npoints(m, Tuple)[Dim]) ? 0 : 1
    c = mask / (spacing(m, I, Dim) + forward_spacing(m, I, Dim))
    return (c, -c)
end

@inline function _stencil_weights(
        op::StarDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    m = mesh(space)
    mask = I[Dim] == npoints(m, Tuple)[Dim] ? 0 : 1
    # the averaged spacing, which is what the starred difference divides by
    c = 2 * mask / (spacing(m, I, Dim) + forward_spacing(m, I, Dim))
    return (c, -c)
end

# Expanding the definition over the two one-sided differences gives a three-point stencil.
# With S = h + hf,
#
#   D_h(u)_i = h/(S·hf) · u_{i+1} + (hf/(S·h) - h/(S·hf)) · u_i - hf/(S·h) · u_{i-1}
#
# which is where the two coefficients below come from: `a` is the weight of the forward
# neighbour and `b` the magnitude of the backward one.
@inline _stencil_taps(::CrossWeightedDifference) = (Val(1), Val(0), Val(-1))

@inline function _stencil_weights(
        op::CrossWeightedDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    m = mesh(space)

    if I[Dim] == 1
        # No point behind the first one: Dₕ has no truncated-boundary convention of its
        # own, so it collapses to the one-sided difference the near side still gives,
        # D₊(u)_1 = (u_2 - u_1)/h_1 (gpena/Bramble.jl#183).
        a = inv(spacing(m, I, Dim))
        return (a, -a, zero(a))
    elseif I[Dim] == npoints(m, Tuple)[Dim]
        # No point past the last one: collapses to D₋(u)_n = (u_n - u_{n-1})/h_n.
        b = inv(spacing(m, I, Dim))
        return (zero(b), b, -b)
    else
        h = spacing(m, I, Dim)
        hf = forward_spacing(m, I, Dim)
        total = h + hf

        a = h / (total * hf)
        b = hf / (total * h)
        return (a, b - a, -b)
    end
end

# --- Traits ----------------------------------------------------------------------- #

"""
    ExtendedDifferenceNode{D, Dim}

The three difference nodes that are neither one-sided nor a jump, differencing along `Dim`.
Grouped so that everything reading only the direction off a node covers all of them at
once, as `DifferenceNode` does for the one-sided pair.
"""
const ExtendedDifferenceNode{D, Dim} = Union{
    CenteredDifference{D, Dim}, StarDifference{D, Dim}, CrossWeightedDifference{D, Dim}
}

# ==============================================================================
# Composite trial/test functions: ∇ₕ, ∇₊ₕ, εₕ, divₕ over several leaves at once
# ==============================================================================
#
# `form(Wₕ, Vₕ, f)` (bilinear.jl) already hands `f` the space's own `TrialFunction{D,N}`/
# `TestFunction{D,N}`, and that object is already tuple-like: `u(i)` and `components(u)`
# (form/component.jl) address its `N` immediate subspaces since gpena/Bramble.jl#74, and
# `TrialFunction`/`TestFunction` already answer `iterate`/`getindex`/`length`. What is
# missing is passing `u` itself, unindexed, straight to a vectorial operator: `∇ₕ(u)` on a
# composite `u` used to hit the generic `∇ₕ(op::LazyOp{D})` method above, differencing the
# whole composite as if it were one scalar function, rather than each of its `N` components
# in turn (gpena/Bramble.jl#234). The two methods below intercept `TrialFunction{D,N}`/
# `TestFunction{D,N}` ahead of that generic method -- a concrete struct is always more
# specific than the abstract `LazyOp{D}` it is a subtype of, whatever `N` is -- and, only
# when `N` is a genuine composite leaf count, forward to `∇ₕ`'s/`∇₊ₕ`'s own `componentwise`
# tuple method (`@node_family`'s `vectorial_alias`, `node_family.jl`) over `components(u)`:
# an `N`-tuple of `D`-tuples, the gradient tensor. A scalar space (`N === nothing` or
# `N == 1`) has to keep exactly what the generic method already gave it -- reproduced in
# `_∇ₕ_noncomposite`/`_∇₊ₕ_noncomposite` below, rather than falling through to it, since our
# own method is the more specific one for every `N` and would otherwise shadow the scalar
# case too.

@inline _∇ₕ_noncomposite(op::LazyOp{1}) = D₋ₓ(op)
@inline _∇ₕ_noncomposite(op::LazyOp{D}) where {D} = ntuple(dim -> D₋(op, Val(dim)), Val(D))

"""
    ∇ₕ(u::Union{TrialFunction, TestFunction})

The backward gradient tensor of a composite trial or test function `u`: an `N`-tuple (one
per component of `u`) of `D`-tuples (one per spatial direction), `∇ₕ(u)[c][d]` the backward
difference of component `c` along direction `d`.

Equivalent to `∇ₕ(components(u))`, spelled without the explicit `components` call so `u`
alone can be passed to a vectorial operator. On a scalar space (one component) this is the
same `D`-tuple `∇ₕ` already returns for any operator.
"""
@inline function ∇ₕ(op::Union{TrialFunction{D, N}, TestFunction{D, N}}) where {D, N}
    (N isa Integer && N > 1) && return map(∇ₕ, components(op))
    return _∇ₕ_noncomposite(op)
end

@inline _∇₊ₕ_noncomposite(op::LazyOp{1}) = D₊ₓ(op)
@inline _∇₊ₕ_noncomposite(op::LazyOp{D}) where {D} = ntuple(dim -> D₊(op, Val(dim)), Val(D))

"""
    ∇₊ₕ(u::Union{TrialFunction, TestFunction})

The forward twin of [`∇ₕ`](@ref)`(u::Union{TrialFunction,TestFunction})`.
"""
@inline function ∇₊ₕ(op::Union{TrialFunction{D, N}, TestFunction{D, N}}) where {D, N}
    (N isa Integer && N > 1) && return map(∇₊ₕ, components(op))
    return _∇₊ₕ_noncomposite(op)
end

# --- εₕ, divₕ: symmetric strain and staggered divergence over composite functions ---- #
#
# Placement settled by gpena/Bramble.jl#234 (issue comment, 2026-09-18): ε_ii on the face
# centre normal to axis `i` (a bare backward difference, no averaging), ε_ij for `i != j` on
# the edge centre the pair `{i,j}` shares (each side's cross difference averaged once, onto
# that edge), and div u on the cell centre every axis shares. No collocation choice is
# exposed: these are the only placements `εₕ`/`divₕ` build.
#
# Both are builder-only: `εₕ(u)`/`divₕ(u)` return a small struct holding the `D`-many (or
# `D×D`-many) `LazyOp`s the formula above names, and the *only* thing that consumes it is
# the `inner₊` method beside each struct, which expands immediately -- inside the closure
# `form` resolves, before `simplify_ast` ever runs -- into the sum of ordinary single-block
# `BilinearProduct`s a user would write by hand (`test/form/vector_calculus.jl`'s hand-
# expanded reference is exactly that sum). Nothing here is a `LazyOp`, so nothing here ever
# reaches assembly, `local_stencil` or `block_of` directly: the architecture stays "every
# `LazyOp` is scalar-valued, expansion happens at the builder" (gpena/Bramble.jl#234).
#
# `εₕ`/`divₕ` differ from `space/operators/vector_calculus.jl`'s *runtime* `divₕ`
# (gpena/Bramble.jl#158) the way every symbolic/numeric pair in this package can (CONTEXT.md):
# the runtime `divₕ` sums raw backward differences with no cross-axis averaging, read at the
# mesh's own nodes; placing every one of the `D` terms here at the same shared quadrature
# point first is what makes `inner₊(divₕ(u), divₕ(v))` well posed. The name is shared on
# purpose -- both are "the backward-difference divergence" -- and the two are never mixed in
# one expression, so nothing has to choose between them.

@inline function _vc_bwd(op, d::Int)
    d == 1 && return D₋ₓ(op)
    d == 2 && return D₋ᵧ(op)
    return D₋₂(op)
end

@inline function _vc_avg(op, d::Int)
    d == 1 && return Mₓ(op)
    d == 2 && return Mᵧ(op)
    return M₂(op)
end

@inline _stagger_set(i::Int, j::Int) = i == j ? (i,) : (min(i, j), max(i, j))

# The additive pieces of one entry εᵢⱼ(u) of the strain tensor, kept apart rather than
# summed into one node. `ε_ii` is a single piece; `ε_ij` (`i != j`) is the two half-averaged
# cross differences the definition adds together. Keeping them apart is what lets
# `inner₊(::_StrainTensor, ::_StrainTensor)` below expand their cross product into clean
# single-component terms at the builder: a *summed* `ε_ij(u)` mixes trial (or test)
# components `i` and `j` in one subtree, and `simplify_ast`'s component-distribution rule
# only compares one node's class against its sibling's -- once a scale wraps the whole
# tensor's sum and two already-mixing siblings meet, both report the same "mixed" marker and
# the rule cannot tell them apart, leaving the scale over a term `block_of` cannot route.
# Building the four cross terms directly, the way a user would expand `(a+b)*(c+d)` by hand,
# means no node here ever mixes components in the first place.
@inline function _strain_pieces(u, i::Int, j::Int)
    i == j && return (_vc_bwd(u(i), i),)
    return (0.5 * _vc_avg(_vc_bwd(u(i), j), i), 0.5 * _vc_avg(_vc_bwd(u(j), i), j))
end

# One term of the divergence: D_{-i}(u_i), averaged onto the shared cell centre by every
# other axis. `foldl` over a runtime-filtered range, not `ntuple`: this runs once per
# `εₕ`/`divₕ` call (builder time, not per grid point), the same footing
# `docs/src/examples/elasticity_3d.jl`'s `divₜ` already stands on.
@inline _div_term(u, i::Int, ::Val{D}) where {D} = foldl(
    (op, d) -> _vc_avg(op, d), Iterators.filter(!=(i), 1:D); init = _vc_bwd(u(i), i)
)

"""
    Bramble._StrainTensor{D}

Builder-only container for [`εₕ`](@ref)'s `D × D` entries, each held as its additive pieces
(`Bramble._strain_pieces`) rather than their sum. Never reaches assembly or an AST walker:
[`inner₊`](@ref) on two of these expands immediately into the sum of single-block products a
user would write out by hand.
"""
struct _StrainTensor{D, T}
    entries::T
end

"""
    εₕ(u) -> Bramble._StrainTensor

The symbolic small-strain tensor \$\\varepsilon(u) = \\tfrac12(\\nabla u + \\nabla u^{T})\$ of
a composite trial or test function `u` with one component per spatial dimension.

`u` is whatever `form`'s trial or test argument already is: `u(i)` addresses its `i`-th
component exactly as it does everywhere else in the form layer (gpena/Bramble.jl#74). Every
entry is placed the way the discrete energy form needs it, with no collocation choice
exposed -- see this section's header comment for the placement.

The only supported use is `inner₊(εₕ(u), εₕ(v))`, which expands to
``\\sum_{i,j} (\\varepsilon_{ij}(u), \\varepsilon_{ij}(v))_{S_{ij}}`` with
``S_{ii} = \\{i\\}`` and ``S_{ij} = \\{i,j\\}`` for `i != j`, through
[`inner₊`](@ref)`(left, right, Val(S))`.

See also: [`divₕ`](@ref), [`∇ₕ`](@ref).
"""
function εₕ(u::LazyOp{D}) where {D}
    entries = ntuple(Val(D)) do i
        ntuple(Val(D)) do j
            _strain_pieces(u, i, j)
        end
    end
    return _StrainTensor{D, typeof(entries)}(entries)
end

# The cross product of two entries' additive pieces, each pair expanded into its own
# `inner₊(..., Val(S))` term -- the builder-time equivalent of multiplying out `(a+b)*(c+d)`
# by hand, so that every term reaching `inner₊` already carries one component per side and
# `simplify_ast` is never asked to untangle a mixing sum (see `_strain_pieces` above).
@inline _cross_terms(lu::Tuple, lv::Tuple, ::Val{S}) where {S} = _flatten_tuples(
    map(a -> map(b -> inner₊(a, b, Val(S)), lv), lu)
)

@inline function inner₊(left::_StrainTensor{D}, right::_StrainTensor{D}) where {D}
    terms = _flatten_tuples(
        ntuple(Val(D)) do i
        _flatten_tuples(
            ntuple(Val(D)) do j
            _cross_terms(
                left.entries[i][j], right.entries[i][j], Val(_stagger_set(i, j))
            )
        end
        )
    end
    )
    return foldl(+, terms)
end

"""
    Bramble._DivergenceTerms{D}

Builder-only container for [`divₕ`](@ref)'s `D` per-component terms: the symbolic twin of
[`Bramble._StrainTensor`](@ref) for the divergence, and with the same lifetime -- consumed
immediately by [`inner₊`](@ref), never part of an assembled AST.
"""
struct _DivergenceTerms{D, T}
    terms::T
end

"""
    divₕ(u) -> Bramble._DivergenceTerms

The symbolic staggered divergence of a composite trial or test function `u` with one
component per spatial dimension, placed at the cell centre every axis shares: term `i` is
``D_{-,i}(u_i)`` averaged onto that centre by every axis other than `i`.

Shares its name with the *runtime* [`divₕ`](@ref) over grid functions
(`space/operators/vector_calculus.jl`, gpena/Bramble.jl#158); see this section's header
comment for how and why the two differ.

The only supported use is `inner₊(divₕ(u), divₕ(v))`, which expands to
``\\sum_{i,j} (\\mathrm{div}_h^{(i)}(u), \\mathrm{div}_h^{(j)}(v))_{\\{1,\\dots,D\\}}``
through [`inner₊`](@ref)`(left, right, Val(S))`.

See also: [`εₕ`](@ref).
"""
function divₕ(u::LazyOp{D}) where {D}
    terms = ntuple(i -> _div_term(u, i, Val(D)), Val(D))
    return _DivergenceTerms{D, typeof(terms)}(terms)
end

@inline function inner₊(left::_DivergenceTerms{D}, right::_DivergenceTerms{D}) where {D}
    S = Val(ntuple(identity, Val(D)))
    return foldl(
        +, ntuple(Val(D)) do i
            foldl(+, ntuple(Val(D)) do j
                inner₊(left.terms[i], right.terms[j], S)
            end)
        end
    )
end

# --- divcₕ, εcₕ: centered divergence and strain over composite functions ---------------- #
#
# The centered difference is collocated: every `Dc` term sits on the grid point itself, so
# neither builder averages or staggers anything. `divcₕ(u)` is therefore an ordinary scalar
# `LazyOp` sum usable anywhere a test or trial expression is. `εcₕ(u)` keeps its entries'
# additive pieces apart, for the reason `_strain_pieces` above gives, and is consumed only by
# the `innerₕ` method beside it. Both methods take `LazyOp{D}`, which is more specific than
# the runtime `divcₕ(uₕ)`/`εcₕ(uₕ)` over grid functions (untyped) and disjoint from any grid
# function, so the symbolic and numeric families never meet.

@inline function _vc_centered(op, d::Int)
    d == 1 && return Dcₓ(op)
    d == 2 && return Dcᵧ(op)
    return Dc₂(op)
end

"""
    divcₕ(u::LazyOp{D}) -> LazyOp

The symbolic centered divergence of a trial or test function `u` with one component per
spatial dimension,

```math
\\textrm{div}_{c,h}(u) = \\sum_{i=1}^{D} \\textrm{Dc}_{x_i}(u_i).
```

Every term is collocated at the grid point, so the result is a plain operator sum usable
wherever an operator is, e.g. `innerₕ(p, divcₕ(v))`. Shares its name with the runtime
[`divcₕ`](@ref) over grid functions (`space/operators/vector_calculus.jl`).

See also: [`εcₕ`](@ref), [`divₕ`](@ref).
"""
function divcₕ(u::LazyOp{D}) where {D}
    return foldl(+, ntuple(i -> _vc_centered(u(i), i), Val(D)))
end

"""
    Bramble._CenteredStrainTensor{D}

Builder-only container for [`εcₕ`](@ref)'s `D × D` entries, each held as its additive
pieces. Consumed only by [`innerₕ`](@ref) on two of these, never part of an assembled AST.
"""
struct _CenteredStrainTensor{D, T}
    entries::T
end

@inline function _centered_strain_pieces(u, i::Int, j::Int)
    i == j && return (_vc_centered(u(i), i),)
    return (0.5 * _vc_centered(u(i), j), 0.5 * _vc_centered(u(j), i))
end

"""
    εcₕ(u::LazyOp{D}) -> Bramble._CenteredStrainTensor

The symbolic centered small-strain tensor of a composite trial or test function `u`,

```math
\\varepsilon^{ii}_{c,h}(u) = \\textrm{Dc}_{x_i}(u_i), \\qquad
\\varepsilon^{ij}_{c,h}(u) = \\tfrac{1}{2}\\left(\\textrm{Dc}_{x_j}(u_i)
    + \\textrm{Dc}_{x_i}(u_j)\\right), \\quad i \\neq j.
```

The only supported use is `innerₕ(εcₕ(u), εcₕ(v))`, which expands to
``\\sum_{i,j} (\\varepsilon^{ij}_{c,h}(u), \\varepsilon^{ij}_{c,h}(v))_h``. Shares its name
with the runtime [`εcₕ`](@ref) over grid functions.

See also: [`divcₕ`](@ref), [`εₕ`](@ref).
"""
function εcₕ(u::LazyOp{D}) where {D}
    entries = ntuple(Val(D)) do i
        ntuple(j -> _centered_strain_pieces(u, i, j), Val(D))
    end
    return _CenteredStrainTensor{D, typeof(entries)}(entries)
end

@inline function innerₕ(left::_CenteredStrainTensor{D}, right::_CenteredStrainTensor{D}) where {D}
    terms = _flatten_tuples(
        ntuple(Val(D)) do i
        _flatten_tuples(
            ntuple(Val(D)) do j
            _flatten_tuples(
                map(a -> map(b -> innerₕ(a, b), right.entries[i][j]), left.entries[i][j])
            )
        end
        )
    end
    )
    return foldl(+, terms)
end

# ==============================================================================
# Expression rendering (gpena/Bramble.jl#274)
# ==============================================================================

expression(op::BackwardDifference{D, Dim}) where {D, Dim} = "D₋$(_BRAMBLE_var2symbol[Dim])($(expression(op.inner_op)))"
expression(op::ForwardDifference{D, Dim}) where {D, Dim} = "D₊$(_BRAMBLE_var2symbol[Dim])($(expression(op.inner_op)))"
expression(op::CenteredDifference{D, Dim}) where {D, Dim} = "Dc$(_BRAMBLE_var2symbol[Dim])($(expression(op.inner_op)))"
expression(op::StarDifference{D, Dim}) where {D, Dim} = "D̽$(_BRAMBLE_var2symbol[Dim])($(expression(op.inner_op)))"
function expression(op::CrossWeightedDifference{D, Dim}) where {D, Dim}
    "Dₕ$(_BRAMBLE_var2symbol[Dim])($(expression(op.inner_op)))"
end
