# difference.jl
# Discrete finite difference operators for Bramble lazy AST

# ==============================================================================
# Struct Definitions
# ==============================================================================

"""
    BackwardDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node representing a backward finite difference operator acting in dimension `Dim`.
"""
struct BackwardDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

"""
    ForwardDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node representing a forward finite difference operator acting in dimension `Dim`.
"""
struct ForwardDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

# ==============================================================================
# User-Facing API & Overloads
# ==============================================================================
#
# The two one-sided families, generated by `@node_family` (`node_family.jl`). What was
# written out here -- `grad_backward`/`grad_forward`, six subscript one-liners, the two
# gradients and their tuple methods -- is the same text for both families but for the node
# name, so it is now said once (gpena/Bramble.jl#74).
#
# `D₋(op, Val(1))` is the entry point the subscripts forward through, and it is a method of
# the same `D₋` the space layer applies to a grid function: the argument decides whether a
# difference is computed now or a node is built to compute it during assembly.

@node_family(node=BackwardDifference,
    stem=D₋,
    what="backward finite difference",
    vectorial_alias=∇ₕ,
    componentwise=true)

@node_family(node=ForwardDifference,
    stem=D₊,
    what="forward finite difference",
    vectorial_alias=∇₊ₕ,
    componentwise=true)

# ==============================================================================
# Zero-Allocation Stencil Evaluators
# ==============================================================================

# Taps and weights, consumed by the one `local_stencil` in `form/stencil_eval.jl` and --
# the point of declaring them -- by `stencil_offsets` in `form/stencil_pattern.jl`, which
# used to spell the same reach out a second time (gpena/Bramble.jl#70).
@inline _stencil_taps(::BackwardDifference) = (Val(0), Val(-1))
@inline _stencil_taps(::ForwardDifference) = (Val(1), Val(0))

@inline function _stencil_weights(
        op::BackwardDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    h = spacing(mesh(space), I, Dim)
    mask = I[Dim] == 1 ? 0 : 1
    return (mask / h, -mask / h)
end

@inline function _stencil_weights(
        op::ForwardDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    m = mesh(space)
    h = forward_spacing(m, I, Dim)
    mask = I[Dim] == npoints(m, Tuple)[Dim] ? 0 : 1
    return (mask / h, -mask / h)
end

# ==============================================================================
# AST Resolution
# ==============================================================================

# `resolve_ast` for both is generated with the families above.

# ==============================================================================
# Direct integration helpers for the form AST (ast.jl)
# ==============================================================================

"""
    DifferenceNode{D, Dim}

Either one-sided difference node over a `D`-dimensional space, differencing along `Dim`.

The two carry the same parameters, so anything that reads only the *direction* off the
node is written against this alias and stays symmetric between them by construction.

Not everything can be: `inner₊` takes backward differences alone, because the staggered
weights it carries are the ones the summation-by-parts identity pairs with a backward
difference. Use this alias where the distinction genuinely does not arise.
"""
const DifferenceNode{D, Dim} = Union{BackwardDifference{D, Dim}, ForwardDifference{D, Dim}}

# ==============================================================================
# The remaining difference families
# ==============================================================================
#
# Three more differences, each a symbolic counterpart of an operator the space layer
# already provides. These nodes assemble through their stencils; the space layer's matrix
# forms of the same three operators are what those stencils are tested against.
#
# The boundary convention is the one the one-sided nodes already use: the offsets stay and
# the coefficients go to zero. A truncated point contributes nothing while the stencil
# keeps the same shape, which is what lets the assembly loop stay branch-free.
#
# Writing `h` for `spacing` (xᵢ - xᵢ₋₁) and `hf` for `forward_spacing` (xᵢ₊₁ - xᵢ), as the
# space layer's own docstrings do.

"""
    CenteredDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node for the centered difference along `Dim`,

```math
Dc(u)_i = \\frac{u_{i+1} - u_{i-1}}{h_i + h_{i+1}}
```

Truncated at both ends of `Dim`, having no neighbour on one side.
"""
struct CenteredDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

"""
    StarDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node for the starred forward difference along `Dim`,

```math
D^{*}_{+}(u)_i = \\frac{u_{i+1} - u_i}{(h_i + h_{i+1})/2}
```

The forward difference over the *averaged* spacing rather than the forward one, which is
what makes the discrete integration by parts close. Truncated at the far end of `Dim`.
"""
struct StarDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

"""
    CrossWeightedDifference{D,Dim,OpType<:LazyOp{D}} <: LazyOp{D}

An AST node for the cross-weighted centered difference along `Dim`,

```math
D_h(u)_i = \\frac{h_i}{h_i + h_{i+1}} D_{-}(u)_{i+1}
         + \\frac{h_{i+1}}{h_i + h_{i+1}} D_{-}(u)_i
```

The same two one-sided differences the centered difference combines, weighted by the
*opposite* spacings. That swap is what makes it second order on a non-uniform grid where
`Dc` is first, and the two coincide when the spacing is constant. Truncated at both ends.
"""
struct CrossWeightedDifference{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

# The three extended families, as `@node_family` calls like the one-sided pair above. Their
# prose is thinner than the space layer's: the boundary conventions and the order-of-accuracy
# comparisons that `Dcₓ` and `Dₕₓ` carry there describe arithmetic, and the arithmetic of
# these nodes is `_stencil_weights` below, which documents itself.
#
# `Dₕ` is the one family whose stem and tuple-valued alias are the same name, so `Dₕ(op)`
# gives the `D`-tuple and `Dₕ(op, Val(2))` the `y` node. They coexist by arity, which is the
# decision gpena/Bramble.jl#140 asked to be made on purpose rather than by merge.

@node_family(node=CenteredDifference,
    stem=Dc,
    what="centered difference",
    vectorial_alias=Dcₕ)

@node_family(node=StarDifference,
    stem=D̽,
    what="starred forward difference",
    vectorial_alias=D̽ₕ)

@node_family(node=CrossWeightedDifference,
    stem=Dₕ,
    what="cross-weighted centered difference",
    vectorial_alias=Dₕ)

# --- Stencils --------------------------------------------------------------------- #

@inline _stencil_taps(::CenteredDifference) = (Val(1), Val(-1))
@inline _stencil_taps(::StarDifference) = (Val(1), Val(0))

@inline function _stencil_weights(
        op::CenteredDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    m = mesh(space)
    # no neighbour on one side at either end
    mask = (I[Dim] == 1 || I[Dim] == npoints(m, Tuple)[Dim]) ? 0 : 1
    c = mask / (spacing(m, I, Dim) + forward_spacing(m, I, Dim))
    return (c, -c)
end

@inline function _stencil_weights(
        op::StarDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    m = mesh(space)
    mask = I[Dim] == npoints(m, Tuple)[Dim] ? 0 : 1
    # the averaged spacing, which is what the starred difference divides by
    c = 2 * mask / (spacing(m, I, Dim) + forward_spacing(m, I, Dim))
    return (c, -c)
end

# Expanding the definition over the two one-sided differences gives a three-point stencil.
# With S = h + hf,
#
#   D_h(u)_i = h/(S·hf) · u_{i+1} + (hf/(S·h) - h/(S·hf)) · u_i - hf/(S·h) · u_{i-1}
#
# which is where the two coefficients below come from: `a` is the weight of the forward
# neighbour and `b` the magnitude of the backward one.
@inline _stencil_taps(::CrossWeightedDifference) = (Val(1), Val(0), Val(-1))

@inline function _stencil_weights(
        op::CrossWeightedDifference{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    m = mesh(space)

    if I[Dim] == 1
        # No point behind the first one: Dₕ has no truncated-boundary convention of its
        # own, so it collapses to the one-sided difference the near side still gives,
        # D₊(u)_1 = (u_2 - u_1)/h_1 (gpena/Bramble.jl#183).
        a = inv(spacing(m, I, Dim))
        return (a, -a, zero(a))
    elseif I[Dim] == npoints(m, Tuple)[Dim]
        # No point past the last one: collapses to D₋(u)_n = (u_n - u_{n-1})/h_n.
        b = inv(spacing(m, I, Dim))
        return (zero(b), b, -b)
    else
        h = spacing(m, I, Dim)
        hf = forward_spacing(m, I, Dim)
        total = h + hf

        a = h / (total * hf)
        b = hf / (total * h)
        return (a, b - a, -b)
    end
end

# --- Traits ----------------------------------------------------------------------- #

"""
    ExtendedDifferenceNode{D, Dim}

The three difference nodes that are neither one-sided nor a jump, differencing along `Dim`.
Grouped so that everything reading only the direction off a node covers all of them at
once, as `DifferenceNode` does for the one-sided pair.
"""
const ExtendedDifferenceNode{D, Dim} = Union{
    CenteredDifference{D, Dim}, StarDifference{D, Dim}, CrossWeightedDifference{D, Dim}
}
