# jump.jl
#
# The symbolic jump across an interface,
#
#     ⟦u⟧ᵢ = u_{i+1} - u_i
#
# A single definition rather than forward/backward pairs: the jump belongs to the interface
# between two cells rather than to a direction of travel across it.
#
# Arithmetically it is the unscaled forward difference (as `ForwardDifference` carries the 1/h).
# Unlike the space layer, where each jump forwards to its difference counterpart, here it is
# an independent AST node.
#
# Boundary points do not truncate: the absent u_{n+1} is taken as zero, yielding -uₙ at the
# boundary point. This matches the space-layer matrix representation where the final row of
# `jumpₓ(Ωₕ)` is [0, ..., 0, -1].

"""
    JumpNode{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}

AST node representing the jump across interfaces along dimension `Dim`, ``u_{i+1} - u_i``.

Not truncated at the far end: the absent `u_{i+1}` is taken as zero, yielding `-uᵢ` there.
This matches the space-layer matrix convention, whose boundary row preserves `-1`.
"""
struct JumpNode{D, Dim, OpType <: LazyOp{D}} <: LazyOp{D}
    inner_op::OpType
end

# Generated by `@node_family` (`node_family.jl`), as every other node family is
# (gpena/Bramble.jl#74). `jump(op, Val(1))` is the entry point the subscripts forward
# through, and a method of the same `jump` the space layer applies to a grid function.
@node_family(node=JumpNode,
    stem=jump,
    what="jump across the interfaces",
    vectorial_alias=jumpₕ)

# only the forward term goes; the local one stays, which is the -uₙ convention
@inline _stencil_taps(::JumpNode) = (Val(1), Val(0))

@inline function _stencil_weights(
        op::JumpNode{D, Dim}, space, I::CartesianIndex{D}
) where {D, Dim}
    reach = I[Dim] == npoints(mesh(space), Tuple)[Dim] ? 0 : 1
    return (reach, -1)
end
