module SpaceOperatorDocstringsTests

using Test
using Bramble

# The 70 directional aliases and the 10 base `!` methods behind them are generated by
# `@operator_family` (`src/space/operators/stencil.jl`), which assembles each docstring from
# the family's prose templates. Nothing else checks that prose: `test/quality/exports.jl`
# only asks that a docstring exists, and a template that silently stops substituting
# `{direction}`, loses a note or drops an `@ref` would pass every other test in the suite.
#
# So the rendered text of all 80 is frozen here. The reference was taken before the
# generators moved off `Core.eval` (gpena/Bramble.jl#258) and is what proves that refactor
# changed no documentation. Renaming an operator changes it on purpose: regenerate with
#
#     BRAMBLE_UPDATE_DOC_SNAPSHOT=1 julia --project=. -e 'using Pkg; Pkg.test("Bramble")'
#
# and read the diff before committing it -- a surprise in that diff is the point of the test.

const STEMS = ("diff₋", "diff₊", "D₋", "D₊", "jump", "M₋", "M₊", "Dstar₊", "Dc", "Dₕ")
const SUFFIXES = ("ₓ", "ᵧ", "₂")
const VECTORIAL = (
    "∇₋ₕ", "∇₊ₕ", "diff₋ₕ", "diff₊ₕ", "jumpₕ", "M₋ₕ", "M₊ₕ", "Dstar₊ₕ", "Dcₕ", "∇ₕ"
)

# The scalar `!` method each family applies a grid function through; it carries the family's
# own docstring for the three centred families and none for the rest, and both cases are
# worth freezing.
const BASE_BANGS = (
    "backward_difference!", "forward_difference!", "backward_finite_difference!",
    "forward_finite_difference!", "forward_star_difference!", "centered_difference!",
    "cross_weighted_difference!", "forward_average!", "backward_average!", "jump!"
)

const REFERENCE = joinpath(@__DIR__, "operator_docstrings.txt")

function documented_names()
    names = String[]
    for stem in STEMS, suffix in SUFFIXES

        push!(names, stem * suffix)
        push!(names, stem * suffix * "!")
    end
    append!(names, VECTORIAL)
    append!(names, BASE_BANGS)
    return names
end

# `MultiDoc.order` rather than `values(md.docs)`: the latter is an `IdDict` keyed by
# signature types, so its iteration order follows object identity and can differ between
# builds of identical code. `order` is the vector Documenter renders from.
function docstring_of(name::AbstractString)
    binding = Base.Docs.Binding(Bramble, Symbol(name))
    meta = Base.Docs.meta(Bramble)
    haskey(meta, binding) || return "<no docstring>"
    multidoc = meta[binding]
    return join([join(multidoc.docs[sig].text) for sig in multidoc.order], "\n---\n")
end

function render()
    io = IOBuffer()
    for name in documented_names()
        println(io, "### ", name)
        println(io, docstring_of(name))
        println(io, "### end ", name)
    end
    return String(take!(io))
end

@testset "Operator docstrings" begin
    current = render()

    if get(ENV, "BRAMBLE_UPDATE_DOC_SNAPSHOT", "0") == "1"
        write(REFERENCE, current)
        @info "operator docstring reference regenerated" REFERENCE
    end

    @testset "every generated name is documented" begin
        for name in documented_names()
            @test isdefined(Bramble, Symbol(name))
        end
        # Only the aliases are required to carry prose: the base `!` methods of the
        # one-sided families document themselves through their matrix form instead.
        for name in documented_names()
            endswith(name, "!") && !occursin("_", name) || continue
            @test docstring_of(name) != "<no docstring>"
        end
    end

    @testset "docstrings match the committed reference" begin
        @test isfile(REFERENCE)
        @test read(REFERENCE, String) == current
    end
end

end # module
